package bedctl

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenAndReadServerConfig(t *testing.T) {
	dir := t.TempDir()
	if err := GenServerConfig(dir, 8080, "admin", "s3cret"); err != nil {
		t.Fatal(err)
	}
	port, err := ReadServerPort(dir)
	if err != nil || port != 8080 {
		t.Fatalf("port = %d, %v", port, err)
	}
	host, _ := ReadServerHost(dir)
	if host != "0.0.0.0" {
		t.Fatalf("host = %q", host)
	}
	db, _ := ReadDBPath(dir)
	if db != "./data/bedrock.sqlite" {
		t.Fatalf("db path = %q", db)
	}
	info, err := os.Stat(filepath.Join(dir, "config.yaml"))
	if err != nil || info.Mode().Perm() != 0o600 {
		t.Fatalf("config mode = %v, %v", info.Mode(), err)
	}
}

func TestSetServerPortPreservesCommentsAndSecrets(t *testing.T) {
	dir := t.TempDir()
	if err := GenServerConfig(dir, 8080, "admin", "s3cret"); err != nil {
		t.Fatal(err)
	}
	before, _ := ReadDBPath(dir)
	if err := SetServerPort(dir, 3000); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "config.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	port, err := ReadServerPort(dir)
	if err != nil || port != 3000 {
		t.Fatalf("port after edit = %d, %v", port, err)
	}
	// The port must stay a bare integer: a quoted "3000" breaks int-typed loaders.
	if !strings.Contains(text, "  port: 3000\n") {
		t.Fatalf("port line not a bare integer:\n%s", text)
	}
	if strings.Contains(text, `port: "3000"`) || strings.Contains(text, `port: '3000'`) {
		t.Fatalf("port got quoted:\n%s", text)
	}
	for _, want := range []string{
		"# Generated by bedctl at",
		"# driver: sqlite | postgres | mysql",
		"# DSH / opencode harness 默认关闭",
		`password: "s3cret"`,
		before,
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("edited config lost content %q:\n%s", want, text)
		}
	}
	// host must remain untouched
	host, _ := ReadServerHost(dir)
	if host != "0.0.0.0" {
		t.Fatalf("host after edit = %q", host)
	}
}

func TestGenAgentConfigAndAddrEdit(t *testing.T) {
	dir := t.TempDir()
	if err := GenAgentConfig(dir, ":9091", "tok-123"); err != nil {
		t.Fatal(err)
	}
	addr, _ := ReadAgentAddr(dir)
	if addr != ":9091" {
		t.Fatalf("addr = %q", addr)
	}
	token, _ := ReadAgentToken(dir)
	if token != "tok-123" {
		t.Fatalf("token = %q", token)
	}
	if err := SetAgentAddr(dir, "0.0.0.0:7070"); err != nil {
		t.Fatal(err)
	}
	addr, _ = ReadAgentAddr(dir)
	if addr != "0.0.0.0:7070" {
		t.Fatalf("addr after edit = %q", addr)
	}
	// token line must stay
	if token, _ = ReadAgentToken(dir); token != "tok-123" {
		t.Fatalf("token lost: %q", token)
	}
	data, _ := os.ReadFile(filepath.Join(dir, "bedrock-agent.yaml"))
	if !strings.Contains(string(data), `# tls_cert: "/path/to/cert.pem"`) {
		t.Fatalf("comment lost:\n%s", data)
	}
}

func TestAgentPort(t *testing.T) {
	tests := []struct {
		addr string
		want uint16
		ok   bool
	}{
		{":9091", 9091, true},
		{"0.0.0.0:9091", 9091, true},
		{":80", 80, true},
		{"bogus", 0, false},
		{"", 0, false},
	}
	for _, tt := range tests {
		got, err := AgentPort(tt.addr)
		if tt.ok && (err != nil || got != tt.want) {
			t.Fatalf("AgentPort(%q) = %d, %v; want %d", tt.addr, got, err, tt.want)
		}
		if !tt.ok && err == nil {
			t.Fatalf("AgentPort(%q) expected error", tt.addr)
		}
	}
}
