package bedctl

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// RandHex returns n random bytes hex-encoded, for secrets.
func RandHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

// GenServerConfig writes the initial config.yaml (never called when one
// already exists — existing configs are preserved untouched).
func GenServerConfig(dir string, port int, adminUser, adminPass string) error {
	key, err := RandHex(32)
	if err != nil {
		return err
	}
	jwt, err := RandHex(32)
	if err != nil {
		return err
	}
	cfg := fmt.Sprintf(`# Generated by bedctl at %s. Edit as needed.
# 生产加固建议: HTTPS 反代、修改默认端口、按需关闭 auth.allow_register。

server:
  port: %d
  host: "0.0.0.0"

# driver: sqlite | postgres | mysql（改 driver 不搬迁数据，2.0 仅支持全新安装）
database:
  driver: sqlite
  path: "./data/bedrock.sqlite"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 1h

jwt:
  secret: "%s"
  access_ttl: "2h"
  refresh_ttl: "168h"

build:
  max_concurrent: 3
  workspace_dir: "./data/workspaces"
  artifact_dir: "./data/artifacts"
  log_dir: "./data/logs"
  cache_dir: "./data/caches"

storage:
  root: "./data/storage"
  attachment_max_bytes: 20971520
  doc_import_max_bytes: 104857600

encryption:
  key: "%s"

admin:
  username: "%s"
  password: "%s"
  display_name: "管理员"

auth:
  allow_register: true

# DSH / opencode harness 默认关闭，装好对应 CLI 后再打开。
dsh:
  enabled: false
  bin: "dsh"
  home: "./data/dsh"
  workspace_root: "./data/dsh-workspaces"
  port: 17800
  startup_timeout: "60s"
  health_interval: "10s"
  auto_restart: true
  approval_mode: "manual"
  pending_ttl: "10m"
  session_idle_ttl: "72h"
  log_dir: ""
  max_sessions: 64

harness:
  enabled: false
  backend: "opencode"
  bin: "opencode"
  port: 4096
  approval_mode: "manual"
`, time.Now().Format("2006-01-02 15:04:05"), port, jwt, key, adminUser, adminPass)
	path := dir + "/config.yaml"
	if err := os.WriteFile(path, []byte(cfg), 0o600); err != nil {
		return err
	}
	return nil
}

// GenAgentConfig writes the initial bedrock-agent.yaml.
func GenAgentConfig(dir, addr, token string) error {
	cfg := fmt.Sprintf(`# Generated by bedctl at %s.
addr: "%s"
token: "%s"
# tls_cert: "/path/to/cert.pem"
# tls_key: "/path/to/key.pem"
`, time.Now().Format("2006-01-02 15:04:05"), addr, token)
	path := dir + "/bedrock-agent.yaml"
	if err := os.WriteFile(path, []byte(cfg), 0o600); err != nil {
		return err
	}
	return nil
}

// flexInt accepts both bare and quoted YAML scalars for numeric fields.
type flexInt int

func (f *flexInt) UnmarshalYAML(node *yaml.Node) error {
	s := strings.TrimSpace(node.Value)
	if s == "" || s == "~" || s == "null" {
		*f = 0
		return nil
	}
	n, err := strconv.Atoi(s)
	if err != nil {
		return fmt.Errorf("行 %d: %q 不是合法端口号", node.Line, node.Value)
	}
	*f = flexInt(n)
	return nil
}

type serverConfigHead struct {
	Server struct {
		Port flexInt `yaml:"port"`
		Host string  `yaml:"host"`
	} `yaml:"server"`
	Database struct {
		Path string `yaml:"path"`
	} `yaml:"database"`
}

// ReadServerPort parses server.port from dir/config.yaml; 0 when absent.
func ReadServerPort(dir string) (int, error) {
	data, err := os.ReadFile(dir + "/config.yaml")
	if err != nil {
		return 0, err
	}
	var head serverConfigHead
	if err := yaml.Unmarshal(data, &head); err != nil {
		return 0, err
	}
	return int(head.Server.Port), nil
}

// ReadServerHost parses server.host; "" when absent.
func ReadServerHost(dir string) (string, error) {
	data, err := os.ReadFile(dir + "/config.yaml")
	if err != nil {
		return "", err
	}
	var head serverConfigHead
	if err := yaml.Unmarshal(data, &head); err != nil {
		return "", err
	}
	return head.Server.Host, nil
}

// ReadDBPath parses database.path (relative to the install dir).
func ReadDBPath(dir string) (string, error) {
	data, err := os.ReadFile(dir + "/config.yaml")
	if err != nil {
		return "", err
	}
	var head serverConfigHead
	if err := yaml.Unmarshal(data, &head); err != nil {
		return "", err
	}
	return head.Database.Path, nil
}

type agentConfigHead struct {
	Addr  string `yaml:"addr"`
	Token string `yaml:"token"`
}

// ReadAgentAddr parses the top-level addr from bedrock-agent.yaml.
func ReadAgentAddr(dir string) (string, error) {
	data, err := os.ReadFile(dir + "/bedrock-agent.yaml")
	if err != nil {
		return "", err
	}
	var head agentConfigHead
	if err := yaml.Unmarshal(data, &head); err != nil {
		return "", err
	}
	return strings.TrimSpace(head.Addr), nil
}

// ReadAgentToken parses the top-level token from bedrock-agent.yaml.
func ReadAgentToken(dir string) (string, error) {
	data, err := os.ReadFile(dir + "/bedrock-agent.yaml")
	if err != nil {
		return "", err
	}
	var head agentConfigHead
	if err := yaml.Unmarshal(data, &head); err != nil {
		return "", err
	}
	return head.Token, nil
}

// AgentPort extracts the port from an addr like ":9091" or "0.0.0.0:9091".
func AgentPort(addr string) (uint16, error) {
	p := addr
	if i := strings.LastIndex(p, ":"); i >= 0 {
		p = p[i+1:]
	}
	n, err := strconv.Atoi(p)
	if err != nil || n <= 0 || n > 65535 {
		return 0, fmt.Errorf("无法从监听地址 %q 解析端口", addr)
	}
	return uint16(n), nil
}

// setYAMLValue edits a nested scalar key (e.g. server.port, addr) in place,
// preserving comments and unrelated content via a yaml.Node round-trip.
// Indentation is kept at 2 spaces to match the generated config layout.
func setYAMLValue(path string, newValue string, keyPath ...string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return fmt.Errorf("解析 %s: %w", path, err)
	}
	if len(doc.Content) == 0 {
		return fmt.Errorf("%s 不是有效的 YAML 映射", path)
	}
	node := doc.Content[0]
	for i, key := range keyPath {
		last := i == len(keyPath)-1
		if node.Kind != yaml.MappingNode {
			return fmt.Errorf("%s: %s 不是映射，无法修改", path, key)
		}
		var child *yaml.Node
		for j := 0; j+1 < len(node.Content); j += 2 {
			if node.Content[j].Value == key {
				child = node.Content[j+1]
				break
			}
		}
		if child == nil {
			if !last {
				return fmt.Errorf("%s 缺少 %s 段，无法修改", path, strings.Join(keyPath, "."))
			}
			// Append the missing final key; yaml.v3 emits the mapping's indent.
			tag, style := scalarTagAndStyle(newValue)
			node.Content = append(node.Content,
				&yaml.Node{Kind: yaml.ScalarNode, Value: key, Tag: "!!str"},
				&yaml.Node{Kind: yaml.ScalarNode, Value: newValue, Tag: tag, Style: style},
			)
			break
		}
		if last {
			tag, style := scalarTagAndStyle(newValue)
			child.Value = newValue
			child.Tag = tag
			child.Style = style
		} else {
			node = child
		}
	}
	var out bytes.Buffer
	enc := yaml.NewEncoder(&out)
	enc.SetIndent(2)
	if err := enc.Encode(&doc); err != nil {
		return err
	}
	if err := enc.Close(); err != nil {
		return err
	}
	tmp := path + ".bedctl-tmp"
	if err := os.WriteFile(tmp, out.Bytes(), 0o600); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// scalarTagAndStyle picks the YAML tag/style for a replacement scalar:
// numeric values stay plain !!int (a quoted "8080" would break int-typed
// config loading), values containing ':' (listen addresses) stay quoted
// strings, other strings are plain !!str.
func scalarTagAndStyle(v string) (string, yaml.Style) {
	if _, err := strconv.Atoi(v); err == nil {
		return "!!int", 0
	}
	if strings.Contains(v, ":") {
		return "!!str", yaml.DoubleQuotedStyle
	}
	return "!!str", 0
}

// SetServerPort changes server.port in dir/config.yaml, keeping comments.
func SetServerPort(dir string, port int) error {
	return setYAMLValue(dir+"/config.yaml", strconv.Itoa(port), "server", "port")
}

// SetAgentAddr changes the top-level addr in dir/bedrock-agent.yaml.
func SetAgentAddr(dir, addr string) error {
	return setYAMLValue(dir+"/bedrock-agent.yaml", addr, "addr")
}
