/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./src/components/app-breadcrumb/app-breadcrumb.vue')['default']
    AppWorkspaceTabs: typeof import('./src/components/app-workspace-tabs/app-workspace-tabs.vue')['default']
    BrandLogo: typeof import('./src/components/brand-logo/brand-logo.vue')['default']
    BuildLogViewer: typeof import('./src/components/build-log-viewer/build-log-viewer.vue')['default']
    DashboardAgentRunCard: typeof import('./src/components/dashboard-agent-run-card/dashboard-agent-run-card.vue')['default']
    DashboardBuildCard: typeof import('./src/components/dashboard-build-card/dashboard-build-card.vue')['default']
    DashboardGrid: typeof import('./src/components/dashboard-grid/dashboard-grid.vue')['default']
    DashboardSystemInfoCard: typeof import('./src/components/dashboard-system-info-card/dashboard-system-info-card.vue')['default']
    DashboardSystemStatusCard: typeof import('./src/components/dashboard-system-status-card/dashboard-system-status-card.vue')['default']
    DashboardWidgetHost: typeof import('./src/components/dashboard-grid/dashboard-widget-host.vue')['default']
    FormDialog: typeof import('./src/components/form-dialog/form-dialog.vue')['default']
    MarkdownScrollPane: typeof import('./src/components/markdown-viewer/markdown-scroll-pane.vue')['default']
    MarkdownViewer: typeof import('./src/components/markdown-viewer/markdown-viewer.vue')['default']
    NotificationBell: typeof import('./src/components/notification-bell/notification-bell.vue')['default']
    ProTable: typeof import('./src/components/pro-table/pro-table.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAction: typeof import('@veltra/desktop')['UAction']
    UActionGroup: typeof import('@veltra/desktop')['UActionGroup']
    UBadge: typeof import('@veltra/desktop')['UBadge']
    UBreadcrumb: typeof import('@veltra/desktop')['UBreadcrumb']
    UButton: typeof import('@veltra/desktop')['UButton']
    UCard: typeof import('@veltra/desktop')['UCard']
    UCardContent: typeof import('@veltra/desktop')['UCardContent']
    UCardHeader: typeof import('@veltra/desktop')['UCardHeader']
    UCheckbox: typeof import('@veltra/desktop')['UCheckbox']
    UCodeEditor: typeof import('@veltra/desktop')['UCodeEditor']
    UContextmenu: typeof import('@veltra/desktop')['UContextmenu']
    UDatePicker: typeof import('@veltra/desktop')['UDatePicker']
    UDialog: typeof import('@veltra/desktop')['UDialog']
    UDrawer: typeof import('@veltra/desktop')['UDrawer']
    UDropdown: typeof import('@veltra/desktop')['UDropdown']
    UEmpty: typeof import('@veltra/desktop')['UEmpty']
    UFilePicker: typeof import('@veltra/desktop')['UFilePicker']
    UForm: typeof import('@veltra/desktop')['UForm']
    UFormItem: typeof import('@veltra/desktop')['UFormItem']
    UGroupInput: typeof import('@veltra/desktop')['UGroupInput']
    UGroupNav: typeof import('@veltra/desktop')['UGroupNav']
    UIcon: typeof import('@veltra/desktop')['UIcon']
    UInput: typeof import('@veltra/desktop')['UInput']
    UMultiSelect: typeof import('@veltra/desktop')['UMultiSelect']
    UNumberInput: typeof import('@veltra/desktop')['UNumberInput']
    UPaginator: typeof import('@veltra/desktop')['UPaginator']
    UPasswordInput: typeof import('@veltra/desktop')['UPasswordInput']
    UProgress: typeof import('@veltra/desktop')['UProgress']
    URadioGroup: typeof import('@veltra/desktop')['URadioGroup']
    UScroll: typeof import('@veltra/desktop')['UScroll']
    USelect: typeof import('@veltra/desktop')['USelect']
    USteps: typeof import('@veltra/desktop')['USteps']
    USwitch: typeof import('@veltra/desktop')['USwitch']
    UTable: typeof import('@veltra/desktop')['UTable']
    UTabs: typeof import('@veltra/desktop')['UTabs']
    UTabsHorizontal: typeof import('@veltra/desktop')['UTabsHorizontal']
    UTabsVertical: typeof import('@veltra/desktop')['UTabsVertical']
    UTag: typeof import('@veltra/desktop')['UTag']
    UTextarea: typeof import('@veltra/desktop')['UTextarea']
    UTree: typeof import('@veltra/desktop')['UTree']
    UTreeSelect: typeof import('@veltra/desktop')['UTreeSelect']
  }
}
